workflows:
  ios-build:
    name: Build iOS IPA (Capacitor)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: "18.20.0"
      vars:
        APP_IDENTIFIER: "com.example.flydronics"
      xcode: latest
    scripts:
      - name: Install node dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Capacitor sync & CocoaPods
        script: |
          npx cap sync ios
          cd ios/App
          pod repo update || true
          pod install --project-directory=.
      - name: Return to project root
        script: |
          cd $CM_PROJECT_DIR
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build/IPA -exportOptionsPlist exportOptions.plist
    artifacts:
      - ios/App/build/IPA/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    cache:
      cache_paths:
        - $HOME/.cocoapods
        - ios/App/Pods

  preview:
    name: Preview Web App
    max_build_duration: 30
    environment:
      node: "18.20.0"
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Start dev server
        script: |
          npm start -- --host 0.0.0.0 &
          sleep 10
    preview:
      port: 5173
      name: Web Preview

# Notes:
# - Configure code signing under the Codemagic UI (Automatic signing with Apple ID or upload certificates & provisioning profiles).
# - If you prefer ad-hoc or enterprise export, change `export_method` above to `ad-hoc` or `enterprise`.
# - The workflow runs `npm run build`, so if your Capacitor app is set to use a remote `server.url`, you can remove the build step.
# - Set any required environment variables and secrets (Apple ID, App-specific password, TEAM_ID) in Codemagic UI.
